### ISSUE TITLE
[vue2] The requested module does not provide an export named 'computed'

### ISSUE THREAD

**Issue by mariusa** [JohnCampionJr/vite-plugin-vue-layouts#10]
Hi, would you please consider making `vite-plugin-vue-layouts` compatible with vue2 as well?

https://github.com/hannoeru/vite-plugin-pages works fine with vite & vue2. 

Adding layouts doesn't work though, as this
https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/44d27894f1baf6b4f3011c4531af6fc23d6db9de/src/RouteLayout.ts#L8

results in
`The requested module does not provide an export named 'computed'`

Any suggestions on how to tackle this?

Thanks for considering!

**Comment by mariusa** [comment]
Looks like this provides `computed` 
https://github.com/vuejs/composition-api/search?q=computed

but needs to be imported like this?
`import { ref, reactive } from '@vue/composition-api'`

Or, maybe vue version could be checked and for vue2 don't import computed, as it just works (I think)

**Comment by mariusa** [comment]
`vue-router-layout` works fine with vite and vue2, so I'll keep that until vue3.

**Comment by Batyodie** [comment]
@mariusa  Hello. Please tell me how you could make friends vue-router-layout + vite-plugin-pages + vue 2.
I keep catching the "Maximum call stack size exceeded" error and don't know how to fix it.

I took the assembly as a basis.
https://github.com/lstoeferle/vite-vue2-windicss-starter

And an example of using vue-router-layout from here.

https://github.com/antfu/vitesse

I created a repository with my problem, you can see

https://github.com/Batyodie/vite-starter-vue2

Here is a screenshot of the error.
![image](https://user-images.githubusercontent.com/61266300/124353443-07089800-dc20-11eb-8edd-29728c2a9d0d.png)

Screenshot of my router file.
![image](https://user-images.githubusercontent.com/61266300/124353580-d9701e80-dc20-11eb-9f33-abc472ac3ec9.png)

My main js file.
![image](https://user-images.githubusercontent.com/61266300/124353613-ff95be80-dc20-11eb-92a0-26cdfa67396f.png)

**Comment by mariusa** [comment]
Hi, I've moved to vue3... I think I started from https://github.com/matt-auckland/vite-vue2-starter and added layout, it just worked for me.
