### ISSUE TITLE
vite hmr doesn't work when modify the style block of layout sfc file

### ISSUE THREAD

**Issue by xiangnanscu** [JohnCampionJr/vite-plugin-vue-layouts#104]
# reproducing link
https://github.com/xiangnanscu/v.git
# steps
the layout file is `src/layouts/default.vue`.
just goto http://localhost:5173/#/Test, you will see the layout file doesn't even show. Even it shows, vite hmr doesn't work when modify the style block of layout file.

also I've a question, does `vite-plugin-vue-layouts` rely on `vite-plugin-pages` ? Does `vite-plugin-vue-layouts` work with `unplugin-vue-router` without `vite-plugin-pages`?

**Comment by markthree** [comment]
@xiangnanscu I rewrote this plugin 👉 [vite-plugin-vue-meta-layouts](https://github.com/dishait/vite-plugin-vue-meta-layouts)。Using a simpler scheme, hmr is more accurate。

**Comment by JohnCampionJr** [comment]
if you're still struggling with this, take a look at this:

```
const router = createRouter({
  history: createWebHashHistory(import.meta.env.BASE_URL),
  extendRoutes: (routes) => {
    setupLayouts(routes)
    return routes
  },
});
```

You're not returning the setupLayouts result:
```
const router = createRouter({
  history: createWebHashHistory(import.meta.env.BASE_URL),
  extendRoutes: (routes) => {
    return setupLayouts(routes)
  },
});
```
