### ISSUE TITLE
Routing has one more layer of nesting

### ISSUE THREAD

**Issue by tanhh326** [JohnCampionJr/vite-plugin-vue-layouts#106]
```js
import { setupLayouts } from 'virtual:generated-layouts';
import generatedRoutes from 'virtual:generated-pages';
```
the generatedRoutes :
![image](https://user-images.githubusercontent.com/82007768/230428044-b2b65004-562f-4077-809b-00e8842f6902.png)

used setupLayouts :
![image](https://user-images.githubusercontent.com/82007768/230428341-1e5e80d1-ed2b-4198-8d22-e37e733604e0.png)

**Comment by JohnCampionJr** [comment]
Not sure what the issue is here, this is what this plugin does, it adds a level to hold the layout.
