### ISSUE TITLE
BUG: 开发时，layouts页面内的样式更新预览页面不会同步更新

### ISSUE THREAD

**Issue by hhun** [JohnCampionJr/vite-plugin-vue-layouts#107]
开发时，`layouts`页面内的样式更新预览页面不会同步更新。
During development, the style update preview page in the `layouts` page will not be updated synchronously

**Comment by kingyue737** [comment]
duplicated #99

**Comment by Z-Shi-Bo** [comment]
兄弟我也是，你的解决了没。

**Comment by hhun** [comment]
> 兄弟我也是，你的解决了没。

 没有解决，不知道什么原因导致的。

**Comment by Z-Shi-Bo** [comment]
谢了，我准备放弃它了

**Comment by JohnCampionJr** [comment]
Closing as duplicate
