### ISSUE TITLE
source maps are generated, but they have a slight offset

### ISSUE THREAD

**Issue by OrbisK** [JohnCampionJr/vite-plugin-vue-layouts#108]
### Describe the bug

*vite.config.ts*
```ts
{
    build: {
        sourcemap: true
    }
}
```

maps are generated but have a slight offset.

 If i remove `vite-plugin-vue-layouts` sourcemaps are working.

### Reproduction

https://github.com/antfu/vitesse

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 33.67 GB / 63.78 GB
  Binaries:
    Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

**Comment by JohnCampionJr** [comment]
What do you mean by a slight offset?  Can you provide more details?

**Comment by OrbisK** [comment]
If you clone e.g. vitesse and add an error to some layout file the mapped line is not the line where the error is thrown.

I can add more details if you wish. But this will need some time

**Comment by JohnCampionJr** [comment]
I cannot duplicate and source map generation is way beyond anything this plugin does.
