### ISSUE TITLE
Named Views

### ISSUE THREAD

**Issue by ghettoDdOS** [JohnCampionJr/vite-plugin-vue-layouts#109]
### Layout.vue
```vue
<template>
  <main>
    <RouterView name="AppBar" />
    <RouterView />
  </main>
</template>
```
### Page.vue
```vue
<script setup lang="ts">
import TheInput from '@/components/TheInput.vue';
</script>

<template>
  <div>example</div>
</template>

<route lang="yaml">
meta:
  layout: home
components:
  AppBar: TheInput
</route>
```
### Expected Behavior
My 'TheInput' component replace named view.
### Actual Behavior
The router recognizes my component as a string and I get an error.
`Component "AppBar" in record with path "/" is not a valid component. Received "TheInput".`
### Question
How to use NamedView with this plugin.

**Comment by JohnCampionJr** [comment]
This is not a setup we support right now.  If you'd like to submit a PR, go for it :)
