### ISSUE TITLE
default.vue layout always runs

### ISSUE THREAD

**Issue by ctholho** [JohnCampionJr/vite-plugin-vue-layouts#11]
Hi,

I believe I found either a bug – or consider this a feature request. :)

I have an `index.vue` page with a different layout than `default.vue`. Let's say it uses `start-layout.vue`. But, all my other pages in `/pages` use `default.vue`.

When I visit my entry point `index.vue` in the browser, I would expect `default.vue`'s setup function *not* to run – alas, it does. That's a problem for side effects.

### Remediation
Avoid having a `default.vue` in `/layouts`. And configure each page to use a named layout. E.g. `not-default.vue`.

### Reproduction
Please see here: https://codesandbox.io/s/layout-bug-forked-q02kt. In the console, both layouts fire their respective logs.

**Comment by ctholho** [comment]
Playing a bit more with it. I think changing this:
https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/fed74fe66f476327140990f2e9c435e01e2f2cea/src/RouteLayout.ts#L39

to simply be `ref('')` would be enough. Because just a few lines later...

https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/fed74fe66f476327140990f2e9c435e01e2f2cea/src/RouteLayout.ts#L43-L47

You configured `default` as your fallback already.

I tested on my minimal reproduction and saw no immediate issues with that approach but I'm not sure if this is safe.

**Comment by michaelowens** [comment]
I think the problem I have is related to this. I actually use the default layout for most pages, but for the 404 page I use an empty layout. When the app is already loaded and click a link that goes to a 404 all works fine, but if I refresh I can see the default layout for a split second before it goes to the layout used by the 404 page.

**Comment by ctholho** [comment]
@michaelowens: To verify, you could go into your `node_modules/vite-plugin-vue-layouts/dist/index.js` and quickly change this manually:

```diff
export function createRouterLayout(_layouts) {
  return defineComponent(() => {
    const router = useRouter()
    const route = useRoute()

-   const name = ref('default')
+   const name = ref('')
    const layouts = shallowReactive(_layouts)
    const layout = computed(() => layouts[name.value])
  
    async function updateLayout(_name) {
      if (typeof layouts[_name] === 'function')
        layouts[_name] = await resolveLayout(layouts[_name])
      name.value = _name || 'default'
    }
```

**Comment by michaelowens** [comment]
That does seem to fix it! My setup is still fairly small and I'm not using SSG, so I can't test those things.

**Comment by FallDownTheSystem** [comment]
I have the same problem.

**Comment by ctholho** [comment]
I also tested with a `.md` file which uses a `layouts/default.vue`, still works beautifully.

Waiting to hear back from @JohnCampionJr. Hope you are safe and sound?

**Comment by JohnCampionJr** [comment]
Sorry, been swamped.  Will review ASAP

**Comment by husayt** [comment]
@JohnCampionJr seems this fix  is still pending. Is there any problems with the fix above , as issue is quote serious?

**Comment by mariusa** [comment]
I have maybe a related bug: same as reporter initial post, the index uses a different layout.
When loading the app, it works. But when clicking on a link from page.vue to /
```
<router-link to="/">Home</router-link>
```
the / renders with the default layout, instead of the custom layout.

@ctholho do you see the same? If so, does the fix above also fixes this? Thanks

**Comment by ctholho** [comment]
@mariusa did you apply the [hotfix](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/11#issuecomment-808914134)? I don't know if I see the same. There are still some problems, possibly related to #6, which I would consider a different issue.

**Comment by mariusa** [comment]
Argh, I can't replicate anymore (no hotfix applied). Not sure what changed, when reported it was happening on 2 environments.

**Comment by mariusa** [comment]
It happened again, hard to reproduce. It does seem related to slower loading. But even after it loads, the layout doesn't change, remains on the wrong one.

**Comment by mariusa** [comment]
The change in this issue didn't fix it (`const name = ref('')`); also restarted.
Nor the fix in https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/14

I've put a log in mounted() for each layout. Starting from default, which is correct 1st time, clicking on a router link which goes to a page using `unauth` layout gives this:
```
default layout mounted
unauth layout mounted
default layout mounted
```
Strange that it's not 100% reproducible.
