### ISSUE TITLE
Declaration File Issue with 'vite-plugin-vue-layouts'

### ISSUE THREAD

**Issue by serkodev** [JohnCampionJr/vite-plugin-vue-layouts#114]
I've encountered an issue while using the 'vite-plugin-vue-layouts' library in my project.

```ts
import Layouts from 'vite-plugin-vue-layouts'
```

When I try to import the library, TypeScript throws the following error:

```
Could not find a declaration file for module 'vite-plugin-vue-layouts'. './node_modules/.pnpm/vite-plugin-vue-layouts@0.8.0_vite@4.3.9_vue-router@4.2.2_vue@3.3.4/node_modules/vite-plugin-vue-layouts/dist/index.mjs' implicitly has an 'any' type.
  There are types at './packages/app/node_modules/vite-plugin-vue-layouts/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vite-plugin-vue-layouts' library may need to update its package.json or typings.ts(7016)
```
### Environment
- Node.js v18.15.0
- TypeScript v5.0.4
- vite-plugin-vue-layouts v0.8.0

**Comment by serkodev** [comment]
Solved with replacing to the following `package.json` config:
```diff
"exports": {
  ".": {
+   "types": "./dist/index.d.ts",
    "require": "./dist/index.js",
    "import": "./dist/index.mjs"
  },
  "./client": {
    "types": "./client.d.ts"
  },
  "./*": "./*"
},
```

I see the latest commit ([b854833](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/commit/b854833476f18667a374dbff3b1ba8877a6853ec)) already changes some `exports` setting which different with npm's [package.json](https://www.npmjs.com/package/vite-plugin-vue-layouts?activeTab=code). 🤔

**Comment by chris-paganon** [comment]
Is there any updates on this? I have the same issue. Modifying the package.json directly inside the node module does the trick but obviously it's not ideal. I do believe it's partly the same issue as #111

**Comment by andersonfelix** [comment]
It's a version problem. Version 0.8.0 was published  **6 months ago**:
- https://www.npmjs.com/package/vite-plugin-vue-layouts

**Comment by hungify** [comment]
Has this problem been solved?

**Comment by andersonfelix** [comment]
@hungify it must update the package version. 

@JohnCampionJr could you do that?

**Comment by RachelYoung94** [comment]
@JohnCampionJr could you please take a look at this issue, preventing me from using this package

**Comment by JohnCampionJr** [comment]
Should be fixed in upcoming update
