### ISSUE TITLE
Is it possible to export the variable `routes`?

### ISSUE THREAD

**Issue by l246804** [JohnCampionJr/vite-plugin-vue-layouts#118]
The default 'setupLayouts' will nest another layer of children in the routes that need to be installed, which is not very good to handle in business use.

I wish I could handle the layout installation myself, but the 'virtual:generated-layouts' module has no exposed type definition and needs to be added manually.

https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/b854833476f18667a374dbff3b1ba8877a6853ec/client.d.ts#L11

**Comment by JohnCampionJr** [comment]
I'm not clear on what you're looking for here; hoping the improved types will fix this.  Otherwise, please let me know.
