### ISSUE TITLE
Different layout for nested routes.

### ISSUE THREAD

**Issue by matpulis** [JohnCampionJr/vite-plugin-vue-layouts#120]
I am trying to set the layout from a nested page and it's not working for me. What I would like to do is use a different layout in pages under the same folder. Layouts only work if its declared in the first file in the pages directory.

**This Works** ,but  both my nested routes get the same layout.
-[src]
-- [pages]
--- profiles.vue [Layout 1]
--- [profiles]
---- view.vue
---- create.vue 

**Not Working**
-[src]
-- [pages]
--- [profiles]
---- view.vue [Layout 1]
---- create.vue [Layout 2] 

Am I missing something here or is this intended behavior?

**Comment by PWie** [comment]
Same for me - I guess that in current implementation on root level pages can have layout defined.
Would be nice to have it improved to allow using different layouts for nested routes.

**Comment by kalaomer** [comment]
I need the same feature, root level is ok but some scenarios this is not enough :/

**Comment by JohnCampionJr** [comment]
For the record this is related to #78 - new route structure
