### ISSUE TITLE
Maybe dynamic suffixes like "tsx", "ts" should be supported?

### ISSUE THREAD

**Issue by l246804** [JohnCampionJr/vite-plugin-vue-layouts#123]
https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/b854833476f18667a374dbff3b1ba8877a6853ec/src/clientSide.ts#L27

**Comment by JohnCampionJr** [comment]
The main plugin already does this; this is only in the clientSide version.  Feel free to submit a PR if needed.
