### ISSUE TITLE
Need to add support for Vite 5.0

### ISSUE THREAD

**Issue by gregmenard** [JohnCampionJr/vite-plugin-vue-layouts#125]
While resolving: vue-base-template@0.1.0
npm ERR! Found: vite@5.0.0
npm ERR! node_modules/vite
npm ERR!   dev vite@"^5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.5.0 || ^3.0.0-0 || ^4.0.0" from vite-plugin-vue-layouts@0.8.0
npm ERR! node_modules/vite-plugin-vue-layouts
npm ERR!   vite-plugin-vue-layouts@"*" from the root project

**Comment by JohnCampionJr** [comment]
Will be in next version
