### ISSUE TITLE
How to set up without requiring layout

### ISSUE THREAD

**Issue by wen403** [JohnCampionJr/vite-plugin-vue-layouts#128]
How to set up without requiring layout

**Comment by markthree** [comment]
> How to set up without requiring layout

I seem to have missed something, the default `Layouts` has already been implemented → [eaaa8c3](https://github.com/johncampionjr/vite-plugin-vue-layouts/commit/eaaa8c3)

**Comment by wen403** [comment]
> > How to set up without requiring layout
> 
> I seem to have missed something, the default `Layouts` has already been implemented → [eaaa8c3](https://github.com/johncampionjr/vite-plugin-vue-layouts/commit/eaaa8c3)

no effect

**Comment by markthree** [comment]
> no effect
@wen403 

Hi, I'm sorry it didn't work, but if you can, please open a new issue with a minimum repository so we can track and fix the issue. 😭

**Comment by Loongphy** [comment]
You can avoid using layout by setting it in your `.vue` file as follows, it works in version 0.11.0. 
If it doesn't work, perhaps you need to restart the program.
```
<route lang="yaml">
  meta:
    layout: false
</route>
```
I'm sorry to comment in a closed issue, but I hope to be able to help others who encounter this problem.
