### ISSUE TITLE
unable to work with `unplugin-vue-router/vite`

### ISSUE THREAD

**Issue by mathieu-gilloots** [JohnCampionJr/vite-plugin-vue-layouts#129]
Hello,  
I think I'm missing something.  
When I create a router, I use the setupLayouts() method.  
In the output of the method, I get the right layout with the page as a children.  
When I output the router.getRoutes(), I didn't get the layout and children only the page.

My code :  
```js
import { createRouter, createWebHistory } from 'vue-router/auto'
import { routes } from 'vue-router/auto/routes'
import { setupLayouts } from 'virtual:generated-layouts'
import type { RouterOptions } from 'vue-router'
import type { UserModule } from '~/types'

const importedRoutesWithLayout = setupLayouts(routes);
export const install: UserModule = (app) => {
  const router = createRouter(<RouterOptions>{
    history: createWebHistory(),
    routes: importedRoutesWithLayout,
  })
  console.log(importedRoutesWithLayout);
  console.log(router.getRoutes());
```

Output : 
![image](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/1282351/a8a4fbae-7ef4-401c-940f-a0c9fed5ce79)

Versions used :  
![image](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/1282351/f6ee49c2-39ce-4de1-94d1-f4cc0d1c9a9c)

Any ideas ?
Thanks

**Comment by JohnCampionJr** [comment]
Nothings jumping out at me.  Can you provide a repro or compare to Vitesse? https://github.com/antfu/vitesse/blob/main/src/main.ts

**Comment by mathieu-gilloots** [comment]
Hello,
Thanks for your answer.
I will try to create a repro.
The difference with vitesse : I'm not using VueSSG.
I create a router.
```
const router = createRouter(<RouterOptions>{
    history: createWebHistory(),
    routes: importedRoutesWithLayout,
  })
```
And I'm passing this router to Vue with `use` method : 
`Vue.use(router)`, before mounting the app.

**Comment by hihanley** [comment]
@mathieu-gilloots 
Look at this: https://github.com/posva/unplugin-vue-router#extendroutes

You need to create router in this way:
```javascript
import { createRouter } from 'vue-router/auto'
import { setupLayouts } from 'virtual:generated-layouts'

const router = createRouter({
  // ...
  extendRoutes: (routes) => setupLayouts(routes),
})
```

**Comment by JohnCampionJr** [comment]
Added this to README

**Comment by kissu** [comment]
Not sure if anything changed but this is my working config with `unplugin-vue-router`

```js
import { setupLayouts } from 'virtual:generated-layouts';
import { createRouter, createWebHistory } from 'vue-router';
import { routes } from 'vue-router/auto-routes';

const router = createRouter({
  history: createWebHistory(),
  routes: setupLayouts(routes),
});
```

`extendRoutes` was undefined for me.
