### ISSUE TITLE
default layout not processed when using sub folder without a layout

### ISSUE THREAD

**Issue by cirolosapio** [JohnCampionJr/vite-plugin-vue-layouts#130]
although a default layout is set when using a sub folder if a layout is not specified in the route tag the default layout is not processed

[`stackblitz`](https://github.com/cirolosapio/vite-plugin-vue-layouts-issue)

**Comment by JohnCampionJr** [comment]
I see it.  You can work around by putting a file sub.vue in the /src with an empty template.

Have to figure out best way to fix it.  Feel free to submit PR if you have an idea

**Comment by cirolosapio** [comment]
i have other routes under the sub folder and the issue persist with all of them

i've run in this issue with the version 0.9.0

**Comment by markthree** [comment]
> although a default layout is set when using a sub folder if a layout is not specified in the route tag the default layout is not processed
> 
> [`stackblitz`](https://github.com/cirolosapio/vite-plugin-vue-layouts-issue)

If your application is not particularly complex, you can try using [ClientSideLayout](https://github.com/JohnCampionJr/vite-plugin-vue-layouts?tab=readme-ov-file#clientsidelayout), which internally handles this issue


this is example 👉 [stackblitz](https://stackblitz.com/edit/github-m83wk6?file=quasar.config.js)

**Comment by hihanley** [comment]
> I see it. You can work around by putting a file sub.vue in the /src with an empty template.我看到了。你可以通过将 sub.vue 文件放在 /src 中，并使用空模板来解决。
> 
> Have to figure out best way to fix it. Feel free to submit PR if you have an idea必须找出解决它的最佳方法。如果您有想法，请随时提交 PR

How about this way?
I have same problem, and it is worked for me.
```javascript
export function setupLayouts(routes) {
  function deepSetupLayout(routes, parentLayout = undefined) {
    return routes.map((route) => {
      // Setup children's layout.
      route.children = deepSetupLayout(route.children ?? [], route.component)

      if (!route.component && route.children.length > 0) {
        // If the route does not have a layout component and contains children, do not setup layout for the route.
        return route
      }
      else {
        // If a layout is specified, use the specified layout.
        // Otherwise, check if the parent layout exists.
        // If the parent layout does not exist, setup default layout.
        return {
          path: route.path,
          component: layouts[route.meta?.layout] || (parentLayout ? undefined : layouts.default),
          children: [{ ...route, path: '' }],
          meta: {
            isLayout: true,
          },
        }
      }
    })
  }

  return deepSetupLayout(routes)
}
```

**Comment by glennmichael123** [comment]
@cirolosapio I have run into this exact issue as well, any routes that are under a folder don't have default layouts in them. The bandaid fix I did was to add this block of code to every vue file I have.

```typescript
<route lang="yaml">
meta:
  layout: default
</route>
```

This now fixes the issue but obviously, this isn't ideal and it's tedious.

**Comment by cirolosapio** [comment]
> @cirolosapio hello, If your application is not particularly complex, you can try using [ClientSideLayout](https://github.com/JohnCampionJr/vite-plugin-vue-layouts?tab=readme-ov-file#clientsidelayout), which internally handles this issue
> 
> this is example 👉 [stackblitz](https://stackblitz.com/edit/github-m83wk6?file=quasar.config.js)

@markthree  I saw the new [ClientSideLayout](https://github.com/JohnCampionJr/vite-plugin-vue-layouts?tab=readme-ov-file#clientsidelayout) but before using it I want to understand what the "limitations" are

> @cirolosapio I have run into this exact issue as well, any routes that are under a folder don't have default layouts in them. The bandaid fix I did was to add this block of code to every vue file I have.
> 
> ```html
> <route lang="yaml">
> meta:
>   layout: default
> </route>
> ```
> 
> This now fixes the issue but obviously, this isn't ideal and it would be tedious.

@glennmichael123  yes i'm using this workaround atm
the default layout is not processed unless specified

**Comment by markthree** [comment]
> @markthree I saw the new [ClientSideLayout](https://github.com/JohnCampionJr/vite-plugin-vue-layouts?tab=readme-ov-file#clientsidelayout) but before using it I want to understand what the "limitations" are

@cirolosapio It only supports three options, `importMode`, `defaultLayout`, `layoutDir`, but defaultLayout supports more options
