### ISSUE TITLE
Nested page render the default layout even set to another layout

### ISSUE THREAD

**Issue by Discreater** [JohnCampionJr/vite-plugin-vue-layouts#134]
I'm using unplugin-vue-router.
![图片](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/41231596/94e928e0-17af-4052-a4b0-7b71cf12d1cb)
![图片](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/41231596/8358c3b7-9958-4d9b-8db9-b6c06c63d138)

pages and layout structure:
```
src/pages
├── about.vue
├── index.vue
└── nested
    └── index.vue

src/layouts
├── alpha.vue
└── default.vue
```

`about.vue` and `nested/index.vue` are set to `alpha` layout. But they have different behavior.

reproduce repo: https://github.com/Discreater/double-layout

**Comment by JohnCampionJr** [comment]
This is a side effect of unplug-vue-router.

You'll need to create a src/pages/nested.vue with its layout set to false to disable the top level layout.

See the unplugin-vue-router example.

I'm going to leave this issue open  in the hopes that we can find a solution but so far I've had no luck.

**Comment by AdamMerrifield** [comment]
Another temporary solution without creating a new file is modifying `routes` before passing them to `setupLayouts`. Effectively doing the same thing.
```JavaScript
const nestedRoute = routes.find((route) => route.path === '/nested')

if (nestedRoute) {
  nestedRoute.meta = nestedRoute.meta ?? {}
  nestedRoute.meta.layout = false
}

const routesWithLayouts = setupLayouts(routes)
```
