### ISSUE TITLE
Params route inherit default layout

### ISSUE THREAD

**Issue by Pash-tet** [JohnCampionJr/vite-plugin-vue-layouts#143]
Hello, i want different layout for [id].vue (layouts/news.vue) and index.vue (layouts/default.vue), but news layout always render inside default layout on :id route ( [#134](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/134) - none of this solutions helps).
![image](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/assets/31577068/9d325794-3973-4f25-8f74-5ceee86ee781)
[Example repo](https://github.com/Pash-tet/vue-plugin-layout-issue)

**Comment by markthree** [comment]
@Pash-tet Please add the `default` layout in `pages/news/index.vue`

```diff
<template>
  <p>/news/index.vue</p>
</template>

+ <route>
+  {
+    meta: {
+      layout: "default"
+    }
+  }
+</route>
```

**Comment by Pash-tet** [comment]
@markthree Thank you for advice, it works !

**Comment by markthree** [comment]
> @markthree Thank you for advice, it works !

You're welcome
