### ISSUE TITLE
Nested Pages - disable Layout

### ISSUE THREAD

**Issue by asaz90** [JohnCampionJr/vite-plugin-vue-layouts#151]
How to apply a different layout on a Page.vue page?
This #144 didn't help :(

```
src/pages
├── index.vue
└── nested
    └── page.vue
    └── index.vue
```

**Comment by Amirovvv** [comment]
If `nested/index.vue` has a layout from its parent, then you won't be able to remove the layout from `nested/page.vue`.

So it is necessary to have `nested/index.vue` manually give the layout, like this:

`nested/index.vue`:
```
<route lang="yaml">
meta:
  layout: default
</route>
```

And for `nested/page.vue`: 
```
<route lang="yaml">
 meta:
   layout: false
 </route>
```
