### ISSUE TITLE
import setupLayouts with 'virtual:' prefix

### ISSUE THREAD

**Issue by ctholho** [JohnCampionJr/vite-plugin-vue-layouts#21]
#9 mentions that `vite-plugin-pages` now uses `import routes from 'virtual:generated-pages'`

Is this something we would want to have ourselves?

I don't know enough about rollup to understand if there is a benefit or if this is simply a convention. In the latter case, I think it looks nicer if we followed their example.

```
import { seputLayouts } from 'virtual:genreated-layouts'
import routes from 'virtual:generated-pages';
```

**Comment by JohnCampionJr** [comment]
Agreed :)   I apologize to all for the delays; life and work have been keeping me from coding; trying to find my way back.

**Comment by JohnCampionJr** [comment]
I do like the clearly labeled use of virtual, so yes, lets do this.  It will be a breaking change.

**Comment by CharlesOkwuagwu** [comment]
Hi, we now get this:

`Cannot find module 'virtual:generated-layouts' or its corresponding type declarations.ts(2307)`

I have updated : `"types": ["vite/client","vite-plugin-vue-layouts/client"],`
