### ISSUE TITLE
postinstall update and build commit breaks 0.3.0 upgrade

### ISSUE THREAD

**Issue by Async0x42** [JohnCampionJr/vite-plugin-vue-layouts#22]
Thanks for the great plugin, but this commit: https://github.com/JohnCampionJr/vite-plugin-vue-layouts/commit/6ddd49c499bf9c0d8fd12db3c7bb7f8053703d65

Seems to cause this error since the src folder is not included when I add vite-plugin-vue-layouts 0.3.0:

```
node_modules/.pnpm/vite-plugin-vue-layouts@0.3.0_vite@2.2.4/node_modules/vite-plugin-vue-layouts: Running postinstall script, failed in 11.6s
.../node_modules/vite-plugin-vue-layouts postinstall$ npm update && npm run build
│ up to date, audited 415 packages in 10s
│ 80 packages are looking for funding
│   run `npm fund` for details
│ found 0 vulnerabilities
│ > vite-plugin-vue-layouts@0.3.0 build
│ > tsup src/index.ts --dts --format cjs,esm
│  CLI  tsup v4.10.1
│ Cannot find src/index.ts
```

The build output is in the npm package dist folder anyways, so I'm able to use the library despite this error

**Comment by climba03003** [comment]
I will stick to version `0.2.2` until the `postinstall` command is removed.

**Comment by mariusa** [comment]
I get a different error
```
> tsup src/index.ts --dts --format cjs,esm

sh: line 1: tsup: command not found
```

Should tsup be added as a dependency of this project?

**Comment by climba03003** [comment]
> 
> 
> I get a different error
> 
> ```
> > tsup src/index.ts --dts --format cjs,esm
> 
> sh: line 1: tsup: command not found
> ```
> 
> Should tsup be added as a dependency of this project?

this package packed without the `src` folder, so this command can never be executed even with `tsup` as dependency.

**Comment by ctholho** [comment]
Sorry. The post-install script slipped into the release. You can safely ignore the error for the moment.

@JohnCampionJr: `postinstall` should probably just be deleted. My intention was so others could easily test with my fork on github without running a bunch of commands.

I had hoped `prepare` would fit the bill but I couldn't get it to run after installing with the scheme: `pnpm add <user>/vite-plugin-vue-layouts#<branch>`. [pnpm has an open issue that seems related](https://github.com/pnpm/pnpm/issues/3157).
