### ISSUE TITLE
readme section about workings and common pattern

### ISSUE THREAD

**Issue by ctholho** [JohnCampionJr/vite-plugin-vue-layouts#25]
I was thinking about issue #12 a bit more and while wondering about how a `useLayout` would work best, I came to the conclusion that the minimum we could do, was to offer a section in the readme that tells users how to implement that functionality with common vue patterns.

That doesn't mean that I think `useLayout` is a bad idea – It's just not a clear-cut advantage to offer easier APIs in a single plugin if we already have established patterns for the same functionality in the wider ecosystem.

Does #24 help a little to alleviate or is it still a rambling mess?

**Comment by JohnCampionJr** [comment]
This is good stuff, thank you!  I'm going to merge the PR but not bump the version since there's no code changes.
