### ISSUE TITLE
Prettier brakes yaml code inside <route>

### ISSUE THREAD

**Issue by AndrewBogdanov** [JohnCampionJr/vite-plugin-vue-layouts#31]
I use prettier on the project, once it's applied content inside <route> tag is getting destroyed.

```
<route lang="yaml">
  meta:
  layout: test
</route>
```
turns into
```
<route lang="yaml">
ium
lead
</route>
```
Could you help me understand how this can be mitigated? Should this part of the code always be put under prettier ignore?

After some investigation I found out that it's caused by the prettier plugin `prettier-plugin-tailwind-css`, will also create an issue in their repo

**Comment by ctholho** [comment]
Hi
You could always use other config langs like "json" – which, to my knowledge is the standard. You would then simply configure the `<route>` block as

```
{ meta: { layout: 'test' } }
```

Take a look at [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages), which implements parsing the `<route>` block and also offers more instructions.

Besides that: I would be lazy and simply claim that it is indeed a bug of a `prettier-plugin-tailwind-css` if it prettifies code that it shouldnt.

**Comment by AndrewBogdanov** [comment]
@ctholho I tried that and it also creates similar issues. Internal JSON gets replaced with some weird parts of tailwindcss class names

**Comment by ctholho** [comment]
Sorry. I'm afraid there is nothing we can do about that from our end. 🙁
