### ISSUE TITLE
Can we provide NUXT style support just use layout in script block?

### ISSUE THREAD

**Issue by byoungd** [JohnCampionJr/vite-plugin-vue-layouts#36]
In nuxt we use layouts in options API in script block
```
{
  layout: 'name'
}
```

I have a project migrated from nuxt to vite which contains a lot  pages, if this plugin support nuxt like style, it will reduce a lot replace work for me.

Thanks a lot!

**Comment by ctholho** [comment]
You can change [line 11](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/703ab791b17572806060d890c7eb12d58c41b0cb/src/RouteLayout.ts#L11) ...

```
      component: layouts[route.meta?.layout || 'default'],
```

... to point to whatever you want to.

If you use something else than [vite-plugin-vue](https://github.com/hannoeru/vite-plugin-pages), I would encourage you to find out how your route object is created. But, the preferred Vue Router way of adding extra infos to routes, is putting them in [`route.meta`](https://next.router.vuejs.org/guide/advanced/meta.html#route-meta-fields)

**Comment by byoungd** [comment]
> You can change [line 11](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/703ab791b17572806060d890c7eb12d58c41b0cb/src/RouteLayout.ts#L11) ...
> 
> ```
>       component: layouts[route.meta?.layout || 'default'],
> ```
> 
> ... to point to whatever you want to.
> 
> If you use something else than [vite-plugin-vue](https://github.com/hannoeru/vite-plugin-pages), I would encourage you to find out how your route object is created. But, the preferred Vue Router way of adding extra infos to routes, is putting them in [`route.meta`](https://next.router.vuejs.org/guide/advanced/meta.html#route-meta-fields)

thanks for reply!
