### ISSUE TITLE
peer dependency warning in vue2

### ISSUE THREAD

**Issue by byoungd** [JohnCampionJr/vite-plugin-vue-layouts#38]
Since this plugin does support vue2, so maybe we should update peer dependency.
Or it will throw warning like this:
```
vite-plugin-vue-layouts@0
.3.1" has incorrect peer dependency "
vue@^3.0.11".
```
Thanks!

**Comment by byoungd** [comment]
> I haven't tested it on Vue2; do you want to make a sample and submit a PR?

Yeah it actually it worked on vue2, I will make a PR later.

**Comment by byoungd** [comment]
> I haven't tested it on Vue2; do you want to make a sample and submit a PR?

I have made a PR to add vue2 example,  check it out and test it if it worked as expected.

**Comment by JohnCampionJr** [comment]
Thanks; will review ASAP.
