### ISSUE TITLE
Error message in VSCode "Cannot find module 'virtual:generated-layouts'"

### ISSUE THREAD

**Issue by wei-beautimode** [JohnCampionJr/vite-plugin-vue-layouts#41]
![](https://i.imgur.com/72kP2Mc.png)

After I upgrade the vite-plugin-vue-layouts  from 0.3.1 to 0.4.0, the error message will be shown.

**Comment by JohnCampionJr** [comment]
Can't duplicate here.  That name didn't change. Is this in a repo you can share?

**Comment by JohnCampionJr** [comment]
I wasn't sure on that one.  My bad.  I will fix it right now.

**Comment by angelhdzmultimedia** [comment]
Excuse me, what was the solution?

I'm using the library along with `unplugin-vue-router`.

The pages load ok.
The layout loads ok.

But I get this error. I know it's related to TypeScript, but I can't find why it isn't generating the types.

Or should I add the types manually?

I already added this in the tsconfig.compilerOptions:

` "types": ["vite-plugin-vue-layouts/client"]`

Any kind reply will be appreciated.

**Comment by ValdoGhafoor** [comment]
@angelhdzmultimedia 
The same issue appeared randomly in the middle of my project.
What was the solution then ? What is inside typed-router.d.ts ?
