### ISSUE TITLE
Layouts with named slots

### ISSUE THREAD

**Issue by csbszb** [JohnCampionJr/vite-plugin-vue-layouts#43]
Hey there,

I've just started experimenting with this plugin and was wondering if it's possible to create layouts with named slots rather than just returning a single router view, something like this?

Layout:
```html
<template>
  <slot name="header">
  <slot name="content">
  <slot name="sidebar">
</template>
```

Then in the actual page:
```html
<template #header>...</template>
<template #content>...</template>
<template #sidebar>...</template>
```
These would need to be wrapped in a custom element, though.

Thanks!

**Comment by csbszb** [comment]
Thanks for the prompt response @ctholho!

I went through the examples, however they don't over this case when not a single/simple `<router-view />` is returned.
I've been struggling to make it work and the only dirty hack solution that worked is this:
https://codesandbox.io/s/funny-dawn-xjlwj

Any chance you have some ideas how this can be done the proper way?  🙏🏻

**Comment by ctholho** [comment]
If you're asking me what is the proper way, I'd say, don't use this plugin for that functionallity. Layouts or `themes` are a very simple way to structure an app but they lack flexibility, which you need in this case.

Basically: Layouts are top-level and pages are their children. You would be changing a parent slot from a child. 

So, what you are doing is exactly the right thing. I wouldn't call it `<Wrapper>` but `<Layout>` and I wouldn't put it in `/components` but `/layouts`. But, basically you're using the most transparent solution proposed by this [blog post](from https://michaelnthiessen.com/advanced-vue-controlling-parent-slots). Section #Lifting State

**Comment by csbszb** [comment]
Thanks for the clarification, it does seem like that in this scenario I would be forcing to use the plugin and not get any gain.
Appreciate you looked into this!
