### ISSUE TITLE
Are nested layouts possible?

### ISSUE THREAD

**Issue by chasegiunta** [JohnCampionJr/vite-plugin-vue-layouts#44]
As far as I can tell, nested layouts don't seem to be possible. Is this something that could be possible in the future?

**Comment by ctholho** [comment]
Hi,
please take a look at the examples to see nested layouts in action.

Also, we have a section in the [readme about how this plugin works](https://github.com/JohnCampionJr/vite-plugin-vue-layouts#how-it-works). And there you will find, that nested layouts are possible via nested router views.

If you mean something else, don't be shy to ask. If I pointed you into the right direction, feel free to close this issue.

**Comment by chasegiunta** [comment]
@ctholho thanks for the quick response. If by nested router views, you mean

```
src/pages/page.vue

<template>
  <h1>My Page</h1>
<template>

<route lang="yaml">
meta:
  layout: first-layout.vue
</route>
```
```
src/layouts/first-layout.vue

<template>
  <router-view />
<template>

<route lang="yaml">
meta:
  layout: second-layout.vue
</route>
```

```
src/layouts/second-layout.vue

<template>
  <router-view />
<template>
```
then unfortunately this isn't working. The contents of second-layout.vue do not render. Am I understanding the usage correctly? I'm using the default configuration, nothing custom.

**Comment by chasegiunta** [comment]
@ctholho I've gone ahead with the way of slotting layouts
(base & shell are also layouts here)

![image](https://user-images.githubusercontent.com/1377169/135726028-88117018-4d32-4383-accb-75c6f8cae43c.png)

Taking this idea a step further, it would be cool to be able to define the nested layouts in the page's layout meta ala
`layout: base/shell/auth`!

**Comment by davidboom95** [comment]
Any plans for supporting this?

**Comment by chasegiunta** [comment]
@davidboom95 I never actually got a response from the maintainer to know if I was perhaps just me implementing it wrong or if the feature actually didn't exist. @JohnCampionJr would you be able to clear this up by chance?

**Comment by JohnCampionJr** [comment]
@chasegiunta @davidboom95 Sorry about that.   No, it doesn't currently support this.  A PR would be welcome though :)

**Comment by markthree** [comment]
Hello, gentlemen, I use this plug-in in my work. My solution is to set up one more top-level file routing for `vite-plugin-pages`。
![image](https://user-images.githubusercontent.com/36569518/156296857-b61cb93e-7743-49b4-b1f9-91fb734f97ba.png)

For details, please see 👉 [vite-plugin-pages/Nested Routes](https://github.com/hannoeru/vite-plugin-pages#nested-routes)

**Comment by markthree** [comment]
Hi @mariusa, yes，To illustrate this scheme, I will provide an example warehouse to illustrate. Please wait a moment

**Comment by markthree** [comment]
@mariusa But note that the latest vite will only run once vite-plugin-vue -layouts in dev start，
and I will try to fix the problem later. Please look forward to it 😁

**Comment by mariusa** [comment]
Thanks @markthree !
At `http://localhost:3000/user` I see
```
top
user index
[to foo](http://localhost:3000/user/foo)
```

The original reporter asked for multiple nested layouts. That is, have content from both `top` & `default`:
```
top
default
user index
[to foo](http://localhost:3000/user/foo)
```

Replacing the default with another layout is already possible.

**Comment by zhuhaobam** [comment]
`This is not the final, but it is also a feasible direction`
`Result like this:`
![image](https://user-images.githubusercontent.com/15319171/180719563-24d47e40-a9f1-40a8-a95b-ed44a12e13b3.png)
`menu structure:`

- views
  - first
     - second
        - third
           - anmial
               - index.vue
           - flower
              - index.vue
        - third.vue
        - youdodo.vue
     - second.vue
     - haododo.vue
  - first.vue
  
`menu structure link:`
https://github.com/zhuhaobam/vtdd/tree/main/src/views

`other link:`
https://github.com/zhuhaobam/vtdd/blob/main/src/layouts/components/sidebar/index.vue
https://github.com/zhuhaobam/vtdd/blob/main/src/utils/router.ts
