### ISSUE TITLE
Layout and ionic router do not mix well

### ISSUE THREAD

**Issue by riderx** [JohnCampionJr/vite-plugin-vue-layouts#46]
Exemple here witht the bug branch :
<img width="852" alt="Screenshot 2021-11-09 at 17 30 10" src="https://user-images.githubusercontent.com/4084527/140974633-b1ae5b9a-efa4-4a14-8594-b1f8f9c4dfca.png">
see the code here:
https://github.com/riderx/vitesse-ionic/tree/bug
if you go to main branch you can see my work around in the `App.vue` file.
i don't understand why it's duplicate the routing with `router-view` in `index.vue`
if i use `ion-router-outlet` liuke in `hi` page you can see the css is broken
<img width="709" alt="Screenshot 2021-11-09 at 17 40 59" src="https://user-images.githubusercontent.com/4084527/140976250-225e3ad2-377e-4fa8-b7e9-d59fe4156b5b.png">

**Comment by JohnCampionJr** [comment]
I don't use or know Ionic so I'm not going to be able to help with this one.

**Comment by riderx** [comment]
Thanks i understand that was not a easy one, after talking with ionc team and reading your code i tried to isolate the issue better and without your plugin i still manage to have it here:
https://github.com/ionic-team/ionic-framework/issues/24192#issuecomment-970424904
So your puging is not involve, i close :)
