### ISSUE TITLE
Getting Error: Invalid route component

### ISSUE THREAD

**Issue by kossa** [JohnCampionJr/vite-plugin-vue-layouts#48]
Hello,

I installed vite-plugin-pages and vite-plugin-vue-layouts when I open "/" I got the error : Invalid route component

My sc/router/index.js:

```js
import { createRouter, createWebHistory } from 'vue-router'
import { setupLayouts } from 'virtual:generated-layouts'
import generatedRoutes from 'virtual:generated-pages'

const routes = setupLayouts(generatedRoutes)

const router = createRouter({
  history: createWebHistory(),
  routes,
})

export default router
```
Dependencies:
```json
"vite-plugin-pages": "^0.18.2",
"vite-plugin-vue-layouts": "^0.5.0",
"vue": "^3.2.16",
"vue-router": "^4.0.12",
"vuex": "^4.0.2"
```

**Comment by JohnCampionJr** [comment]
Hi!  We'd need a repo or something to help figure this out.

**Comment by kossa** [comment]
Sure :
https://github.com/kossa/vite-starter/commit/d393f82822045193387bbf383af733fabcbb1f15

**Comment by JohnCampionJr** [comment]
There are no layouts in the repo; please see [Vitesse](https://github.com/antfu/vitesse) for a full working example
