### ISSUE TITLE
[Feature Request] Provide option to elevate `meta` properties so build-time router can detect

### ISSUE THREAD

**Issue by josh-hemphill** [JohnCampionJr/vite-plugin-vue-layouts#49]
I'm running into issues with trying to get build-time router to be able to access the nested meta properties.
Part of that is an issue with `vite-ssg`'s handling of the router provided in `ctx`, but it would be really nice and convenient to be able to elevate things (like in my case, the language for a dynamic route) to the top level so build-time code attaching to or modifying the top-level routes can have easy access to the meta properties.

**Comment by JohnCampionJr** [comment]
@josh-hemphill I don't use vite-ssg, so I'm not sure I can help provide this but if you want to do a PR, I'd be glad to merge it.
