### ISSUE TITLE
The README is very different from `vite-plugin-pages`

### ISSUE THREAD

**Issue by mesqueeb** [JohnCampionJr/vite-plugin-vue-layouts#53]
https://github.com/JohnCampionJr/vite-plugin-vue-layouts#getting-started

In the getting started section there is this section:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3253920/148146040-b951605e-34f9-4772-80d9-04558f61b5e3.png">

But it's very different from what is required for `vite-plugin-pages`...
Check the readme here:
https://github.com/hannoeru/vite-plugin-pages#vue-1
It says:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/3253920/148146109-a566e717-9b3c-41ea-b0e3-7df957923891.png">

Since this plugin is promoted as a companion to `vite-plugin-pages`, could you add an example of how to integrate both syntaxes?

**Comment by Jimmyzm** [comment]
It looks like 'virtual:generated-pages' & '~pages' they are just alias for each other:
[](https://github.com/hannoeru/vite-plugin-pages/blob/main/client.d.ts)
[](https://github.com/hannoeru/vite-plugin-pages/blob/main/src/constants.ts)

**Comment by JohnCampionJr** [comment]
Honestly, best example is 

https://github.com/antfu/vitesse
