### ISSUE TITLE
Duplicated routes for vanilla vite + router project

### ISSUE THREAD

**Issue by mzenz** [JohnCampionJr/vite-plugin-vue-layouts#55]
Using vite-plugin-vue-layouts in the most vanilla way possible (using vite + vue-router v4) generates duplicated routes.

This [repo](https://github.com/mzenz/vite-plugin-vue-layouts-duplicated-route-bug) reproduces the bug.

# Steps:
```
- git clone https://github.com/mzenz/vite-plugin-vue-layouts-duplicated-route-bug
- cd vite-plugin-vue-layouts-duplicated-route-bug
- yarn && yarn dev
```

# Expected result

Generated routes from `setupLayouts()` should match the routes returned by `router.getRoutes()`.

# Actual result

`router.getRoutes()` shows duplicated routes for each generated route via `setupLayouts()`.

# Note

Likely related to [this issue](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/47) but with a much more stripped-down reproduction to hopefully help with debugging. =)

**Comment by fullstackfool** [comment]
Same here issue here. Looks like it's generating a route for the "parent" layout file too.

**Comment by abitwhy** [comment]
The above repo link is broken. Here is a [minimal reproduction](https://stackblitz.com/edit/vitejs-vite-vvcmax?file=src/pages/index.vue) on [stackblitz](https://stackblitz.com/).

**Comment by Hua-Space** [comment]
Same here issue here. Has anyone found a workaround?

**Comment by paolog22** [comment]
upvote this

**Comment by JohnCampionJr** [comment]
I can duplicate this, but I'm not sure of best way to fix it either

**Comment by JohnCampionJr** [comment]
So there's no way I can figure out to avoid this; it has to do with how vue builds its routes.  I've added a createGetRoutes() function to the spa-side to use in place of `router.getRoutes()` similar to the clientSide version:

https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/1041502cacaf4bcab5cb8ae6406fcfaea0715dba/src/clientSide.ts#L44
