### ISSUE TITLE
Usage without vite-plugin-pages

### ISSUE THREAD

**Issue by RSurya99** [JohnCampionJr/vite-plugin-vue-layouts#57]
This is a really good plugin, but can I use this without vite-plugin-pages?
I have to try some way but doesn't get any conclusion about how to use this plugin without vite-plugin-pages, if you know it please let me know

**Comment by yankeeinlondon** [comment]
i use this with `vite-plugin-pages` and they seem well paired. What doesn't work for you?

**Comment by RSurya99** [comment]
> i use this with `vite-plugin-pages` and they seem well paired. What doesn't work for you?

I can't create custom middleware per page with `vite-plugin-pages`, because I don't know where to put the middleware. I think this is because I don't know where the router array was created when I use `vite-plugin-pages`

**Comment by yankeeinlondon** [comment]
@RSurya99  @AustinWoetzel i have no direct involvement in this plugin but here's what I would say:

- the middleware comment threw me a bit, I think maybe describe what it is you're trying (or wanting) to do as _middleware_ seems like a possible solution to a problem but not a problem
-  in terms of "automatic forwarding" I think this is not really related to this plugig ... probably a bit more aligned with the `vite-plugin-pages` plugin. In this situation, this plugin simply create the routes for you based on file layout and then you connect the plugin with Vue Router in your `main.ts` file. It will look something like this:

```ts
import { ViteSSG } from "vite-ssg";
import { setupLayouts } from "virtual:generated-layouts";
import generatedRoutes from "virtual:generated-pages";
import App from "./App.vue";

const routes = setupLayouts(generatedRoutes);

// https://github.com/antfu/vite-ssg
export const createApp = ViteSSG(App, { routes }, (ctx) => {
  Object.values(import.meta.globEager("./modules/*.ts")).map((i) => i.install?.(ctx));
});
```

This example was just convenient for me but it does use `vite-ssg` too ... anyway the import line is the one in which routes const is setup. As you can see ... pages first sets up the routes, and then this plugin wraps that configuration and layers in route "meta info" for which layout to use.

**Comment by zhuhaobam** [comment]
> @yankeeinlondon我不确定这是否与 RSurya99 的要求有关，但我想做的是设置自动转发，以便我的网站从 / -> /child-page 开始，我不知道该怎么做在插件生成路由时执行此操作。你对我有什么建议吗？

just add index.vue
![image](https://user-images.githubusercontent.com/15319171/183384085-e291f2dd-d961-4ac4-a6ab-df89aa285e8f.png)
