### ISSUE TITLE
How can I generate navigation breadcrumbs?

### ISSUE THREAD

**Issue by zybzzc** [JohnCampionJr/vite-plugin-vue-layouts#61]
Dir tree:
```bash
src/pages
├── posts
│   └── list
│       ├── index.vue
│       └── new
│           └── index.vue
```
The currently generated routes is:
```
{path: '/posts'},
{path: '/posts/new'}
```
So when I am on the `/posts/new` page, the `$route.matched` doesn't includes `/posts` route.

**Comment by zhuhaobam** [comment]
like this  
![image](https://user-images.githubusercontent.com/15319171/183382539-ed60a4c6-4981-467e-9495-a794717fb1fc.png)

For reference, this is a demo
https://github.com/zhuhaobam/vtdd

**Comment by JohnCampionJr** [comment]
This would be beyond the scope of this project.
