### ISSUE TITLE
no layout

### ISSUE THREAD

**Issue by moliu666** [JohnCampionJr/vite-plugin-vue-layouts#64]
Sometimes some pages need no layout ，like /login

```
+------------------+           
| Login            |
|                  |                
+------------------+   
```

But now there is always default layout 

```
+------------------+           
| Default          |
| + -------------+ |            
| |    Login     | |   
+------------------+ 
```

To fix this, I rebuild it

```
// src/RouteLayout.ts - getClientCode
export function setupLayouts(routes) {
  return routes.map(route => {
    const isBoolean = typeof route.meta?.layout === 'boolean'
    if(isBoolean && !route.meta?.layout) {
      return route
    } else {
      let componentName = !isBoolean && route.meta?.layout ? route.meta?.layout : '${options.defaultLayout}'
      return {
        path: route.path,
        component: layouts[componentName],
        children: [ {...route, path: ''} ],
      }
    }
  })
}
```

useage

```
<route lang="yaml">
meta:
  layout: false
</route>
```

if the layout property is a boolean and false, no layout

if the layout property is not a boolean and type inference is true, use layout property as componentName

other, use default layout

**Comment by moliu666** [comment]
Beyond that, I have a more radical idea.

We can provide a hook function for users to customize

The initial idea is as follows

```
// src/RouteLayout.ts - getClientCode
export function setupLayouts(routes, fn) {
  if(tyepof fn === 'function') return fn(routes, layouts, options)
  ...
}
```
When the user provides a function, the default behavior is completely replaced

```
import { createRouter, createWebHistory } from 'vue-router';
import { setupLayouts } from 'virtual:generated-layouts';
import generatedRoutes from '~pages';

const router = createRouter({
  history: createWebHistory(),
  routes: setupLayouts(generatedRoutes, (routes, layouts, options) => {
    // to do someting
    // return routes
  })
});
```

**Comment by itmanyong** [comment]
当不设置插件的defaultLayout选项时,页面没有指定layout的值就不会使用layout
![image](https://user-images.githubusercontent.com/53500371/183245324-3a1b314f-0154-4ace-b4c5-4fbed3655e6d.png)

**Comment by zhuhaobam** [comment]
You may need to do this, manually setlayout
```
const routesLayouts = generatedRoutes.map(v => {
  const currentMenu = v.meta?.layout !== false ? setupLayouts([v])[0] : v
  return currentMenu
})
```

**Comment by zhuhaobam** [comment]
I changed the default address. I changed the index under the layouts directory to the layout definition, so I manually set the layout in the route, so that layout false is set for each page when it is not needed

**Comment by negezor** [comment]
As a solution in my project, I just use a special layout called empty:
```vue
<!-- layouts/empty.vue -->
<template>
    <RouterView v-slot="{ Component }">
        <Suspense>
            <div>
                <component :is="Component" />
            </div>
        </Suspense>
    </RouterView>
</template>
```
Then in the need pages:
```vue
<!-- pages/some-cool-page.vue -->
<route lang="yaml">
meta:
  layout: 'empty'
</route>
```

**Comment by xxxlgloverd** [comment]
> As a solution in my project, I just use a special layout called empty:
> 
> 
> <template>
>     <RouterView v-slot="{ Component }">
>         <Suspense>
>             <div>
>                 <component :is="Component" />
>             </div>
>         </Suspense>
>     </RouterView>
> </template>
> Then in the need pages:
> 
> 
> <route lang="yaml">
> meta:
>   layout: 'empty'
> </route>

use this code is nice but i want to  change  meta: layout ：‘xxx’ this code ,the project cant hmr update，i need restart my project . i want to know how to support modifying meat layout Hmr update?

**Comment by xxxlgloverd** [comment]
> > As a solution in my project, I just use a special layout called empty:
> > 
> > 
> >     
> >         
> >             
> >                 
> >             
> >         
> >     
> > 
> > Then in the need pages:
> > 
> > 
> > meta:
> >   layout: 'empty'
> 
> use this code is nice but i want to change meta: layout ：‘xxx’ this code ,the project cant hmr update，i need restart my project . i want to know how to support modifying meat layout Hmr update?

![Image](https://github.com/user-attachments/assets/2b7289b2-cf3b-4c4e-b3ed-63ec08592444)
i try this way to create routes ，this way can support hmr update but i dont like this way ,can you have a new way to resolve this question?
