### ISSUE TITLE
When to support vite3

### ISSUE THREAD

**Issue by caocaoem** [JohnCampionJr/vite-plugin-vue-layouts#69]
vite-plugin-vue-layouts@0.6.0" has incorrect peer dependency "vite@^2.5.0"

**Comment by ymansurozer** [comment]
Yes please, it is frustrating to see that error every time. There already seems to be a branch so it would be great to merge that into main.

**Comment by JohnCampionJr** [comment]
Fixed in 0.7.0; so sorry for the delay
