### ISSUE TITLE
When using vite-plugin-vue-layouts with vite-plugin-pages the combination of an index route and dynamic route doesn't work

### ISSUE THREAD

**Issue by bux** [JohnCampionJr/vite-plugin-vue-layouts#7]
A simple repro would be:

* Clone [vitesse by antfu](https://github.com/antfu/vitesse) (or create a new github project by using this template)
* Create a new vue file below `~/src/pages/hi` and call it `index.vue`
* Add a `<template/>` with some demo content
* Run `npm run dev`
* Try to open: http://localhost:3333/hi/

Observe how the dynamic route is being used instead of the newly created index route

Issue at vite-plugin-pages: https://github.com/hannoeru/vite-plugin-pages/issues/23

**Comment by ctholho** [comment]
Hi,

`localhost:3000/hi/` and `localhost:3000/hi` are different routes. If you have an index.vue and try to navigate to `localhost:3000/hi` (without the trailing slash), you will find your index.vue working alright. This is expected behaviour.

See e.g. this [blog post about SEO implications of trailing slashes](https://ahrefs.com/blog/trailing-slash/)

**Comment by bux** [comment]
Let me make it a bit clearer:

* Try to open: http://localhost:3333/hi/
* Try to open: http://localhost:3333/hi
* Observe how both requests (with or without trailing slashes) show the dynamic route (`[...all].vue`) and not the index route (`index.vue`)

Ref: https://github.com/hannoeru/vite-plugin-pages/issues/23#issuecomment-799980981

**Comment by ctholho** [comment]
Sorry. I cannot reproduce this with a new vitesse starter template and these versions.
"vue-router": "^4.0.5"
"vite-plugin-pages": "^0.9.0"
"vite-plugin-vue-layouts": "^0.2.2"

**Comment by CharlesOkwuagwu** [comment]
The issue still remains

**Comment by JohnCampionJr** [comment]
Can you check with the new version from today if this is still an issue?  It shouldn't be.
