### ISSUE TITLE
naiveui menu with vite-plugin-vue-layouts and vite-plugin-pages

### ISSUE THREAD

**Issue by zhuhaobam** [JohnCampionJr/vite-plugin-vue-layouts#70]
Can I use it like this

- all routes
![image](https://user-images.githubusercontent.com/15319171/180642043-2988a286-8e2a-4aa1-99b1-95cb8cacbe50.png)

- processed menu
![image](https://user-images.githubusercontent.com/15319171/180642135-c2110f96-c6a8-452c-99ad-348fc56c2a1b.png)

https://github.com/zhuhaobam/vtdd/blob/main/src/layouts/components/sidebar/index.vue

**Comment by zhuhaobam** [comment]
![image](https://user-images.githubusercontent.com/15319171/180642181-c4eb3e64-5e4d-4c14-b442-b06c8eadd6a4.png)

**Comment by zhuhaobam** [comment]
![image](https://user-images.githubusercontent.com/15319171/180676822-3992fa63-49ad-4b6b-900e-4af82dd8608e.png)

https://github.com/zhuhaobam/vtdd/blob/main/src/layouts/components/sidebar/index.vue

**Comment by JohnCampionJr** [comment]
Sorry, this is beyond the scope of this project.
