### ISSUE TITLE
not work with tsx

### ISSUE THREAD

**Issue by zcyc** [JohnCampionJr/vite-plugin-vue-layouts#72]
It dosn't render my layout, always render default layout. And render the meta tag text.
```
export default defineComponent({
  setup() {
    return () => <>
      <route lang="yaml">
        meta:
          layout: home
      </route>
    </>
  },
})
```
![image](https://user-images.githubusercontent.com/9925064/150170853-6d608222-2b03-4a89-b53a-da21eb83f205.png)

**Comment by zhuhaobam** [comment]
Is this code equivalent to template effective

**Comment by zcyc** [comment]
无效的。vite-plugin-vue-layouts 不能用 tsx 中。

**Comment by widcardw** [comment]
I tried to change the layout by changing `route.meta.layout`, but it still does not work. 

```ts
export default defineComponent({
  setup() {
    const route = useRoute()
    route.meta.layout = 'home'

    return () => (
      <>...</>
    )
  }
}
```

**Comment by widcardw** [comment]
https://github.com/hannoeru/vite-plugin-pages#jsxtsx-yaml-format-comments-for-route-datain-vue

Maybe we should turn to the docs of vite-plugin-pages.

**Comment by widcardw** [comment]
You can add a block comment in the JSX/TSX file like below

```js
/*
route

meta:
  layout: home
*/
```

**Comment by zcyc** [comment]
> You can add a block comment in the JSX/TSX file like below
> 
> 
> 
> ```js
> 
> /*
> 
> route
> 
> 
> 
> meta:
> 
>   layout: home
> 
> */
> 
> ```

is this working all right？

**Comment by widcardw** [comment]
> Ok,i read the docs of vite-plugin-pages about parse YAML,But i dont try it. Have you try it?Is it working right？

It works fine, and you can try the repo [widcardw/vue-tsx-starter](https://github.com/widcardw/vue-tsx-starter), the index page is applied with _home layout_. I forgot to deploy it to netlify, but it does work in dev mode.

**Comment by zcyc** [comment]
> > Ok,i read the docs of vite-plugin-pages about parse YAML,But i dont try it. Have you try it?Is it working right？
> 
> 
> 
> It works fine, and you can try the repo [widcardw/vue-tsx-starter](https://github.com/widcardw/vue-tsx-starter), the index page is applied with _home layout_. I forgot to deploy it to netlify, but it does work in dev mode. 

Ok,i will try it. Thank you very much.
