### ISSUE TITLE
feat: able to change the layout programmatically

### ISSUE THREAD

**Issue by mrhammadasif** [JohnCampionJr/vite-plugin-vue-layouts#76]
Nice to have a feature where can change the layout of the current page (when using vite-plugin-pages)

Something similar would be nice:

```vue
<script setup>
const routeMeta = useRouteMeta()
const toggleFullScreen = () => {
  routeMeta.layout = routeMeta.layout === 'fullscreen' ? 'withsidenav' : 'fullscreen'
}
</script>

<route lang="yaml">
meta:
  layout: withsidenav
</route>
```

**Comment by JohnCampionJr** [comment]
You should use a layout that uses dynamic components to accomplish this:
https://vuejs.org/guide/essentials/component-basics.html#dynamic-components
