### ISSUE TITLE
Pages don't render using the setup layout

### ISSUE THREAD

**Issue by boussadjra** [JohnCampionJr/vite-plugin-vue-layouts#81]
### Expectation : 

Render a page inside a layout

### Current state

The pages render correctly, but with setup layout don't do

### Repro

Github repo : https://github.com/boussadjra/vuetify-3-template/tree/vite

Playground :  https://stackblitz.com/github.com/boussadjra/vuetify-3-template/tree/vite

**Comment by JuanxCursed** [comment]
same issue here

**Comment by maietta** [comment]
I've been chasing a bug all day with no apparent fixes.

Basically, generatedRoutes pick up the layouts, but provided routes do not.

No errors, not sure how to diagnose.

**Comment by productdevbook** [comment]
some :/

**Comment by iuriag** [comment]
same here

**Comment by JohnCampionJr** [comment]
Can you provide a clearer explanation of what's wrong?   I looked at the playground and it seems to be working to me.
