### ISSUE TITLE
✨ Add support for `unplugin-vue-router`

### ISSUE THREAD

**Issue by jd-solanki** [JohnCampionJr/vite-plugin-vue-layouts#82]
Hi @JohnCampionJr,

I have been using this plugin for `vite-plugin-pages` and both were doing great. However, vite-plugin-pages doesn't support nuxt 3 like routing.

To resolve this issue, I moved to [unplugin-vue-router](https://github.com/posva/unplugin-vue-router). However, unplugin-vue-router generates nested directory structure instead of a flat one like vite-plugin-pages.

Due to this difference vite-plugin-vue-layouts wrap top most page with the correct layout but for pages inside another directory, there's an incorrect layout that gets wrapped. I hope you will understand from the below picture as you know the implementation.

> _P.S. First array log is a normal routes generated by unplugin-vue-router and second route array is result of wrapping them in `setupLayouts`_

![SCR-20221111-nif](https://user-images.githubusercontent.com/47495003/201331684-96fa0630-727c-4d96-9a2e-195f31d40fc9.png)

**Comment by markthree** [comment]
@jd-solanki I rewrote this plugin。Using a simpler scheme, hmr is more accurate。Due to different principles, there is no such problem。you can try 👉 [vite-plugin-vue-meta-layouts](https://github.com/dishait/vite-plugin-vue-meta-layouts)。And this problem has been solved

**Comment by JohnCampionJr** [comment]
@markthree would you be willing to do a PR for this project?

**Comment by markthree** [comment]
@JohnCampionJr Of course, but I'll test the compatibility with existing plugins

**Comment by markthree** [comment]
@JohnCampionJr I tried it, but it shouldn't work. It's too much of a break. Because [glob-import](https://vitejs.dev/guide/features.html#glob-import) only runs on clients，This means that most of the existing options need to be scrapped or greatly modified! for example `exclude` and `importMode` 😶‍🌫️

**Comment by JohnCampionJr** [comment]
What if we put a new option like 'clientSide' and let users opt into it with the caveats that a few options are lost?

If you're interested, I'd be happy to add you to this repo.

**Comment by markthree** [comment]
@JohnCampionJr nice!! I will try to complete it tomorrow 😁

**Comment by tachibana-shin** [comment]
Related to the problem: I also faced the same problem and i decided to patch [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) instead of patching this plugin you can see the PR here or the `nuxt3` support preview package https://github.com/hannoeru/vite-plugin-pages/pull/435

**Comment by JohnCampionJr** [comment]
Will be in new release; if any further updates needed, let me know.
