### ISSUE TITLE
`layoutsDirs` Option is not working

### ISSUE THREAD

**Issue by JuanxCursed** [JohnCampionJr/vite-plugin-vue-layouts#83]
### Expectation: 
When the `layoutsDirs` option is set to `layouts`, all files inside that folder are expected to be imported and used as layouts on the `<root>/layouts`.

 ### Current state
The layout won't render unless I place it inside of  `src/layouts`

This is my `vite.config.js`:
![image](https://user-images.githubusercontent.com/16026646/202611278-24e06d6b-8467-42df-9201-256879e46348.png)

This is my current folder structure:
![image](https://user-images.githubusercontent.com/16026646/202611431-97d7b42d-d472-4425-a05c-f4c9b32f2377.png)

This is what I do to work:
![image](https://user-images.githubusercontent.com/16026646/202611827-1efdd259-920f-46df-afd7-0fdfe80476f2.png)
![image](https://user-images.githubusercontent.com/16026646/202612181-51d8a63c-8663-49df-a3e6-a7cddb0d6541.png)

**Comment by mazhewei** [comment]
try this:
`layoutsDirs: 'src/layouts',`
btw, `src/layouts` is the default value for this option.

**Comment by JuanxCursed** [comment]
> try this: `layoutsDirs: 'src/layouts',` btw, `src/layouts` is the default value for this option.

Hi @mazhewei, thanks for the reply.

The default option is the only one that is working. Any option filled at `layoutsDirs` property doesn't. 
For instance:
```
{
...
    layoutsDirs: 'layouts' // OR "test/layout",
...
}
```

Doesn't work, the layout files inside of `<root>/layout` or `<root>/test/layout` aren't found,  but with the same configuration if you place the files inside of `src/layouts`, still works.
I believe there is may have a bug in there.

**Comment by JohnCampionJr** [comment]
Just tested with example code in this repo, cannot reproduce.
