### ISSUE TITLE
Use keep-alive component render twice

### ISSUE THREAD

**Issue by codeblockhead** [JohnCampionJr/vite-plugin-vue-layouts#84]
App.vue
<img width="594" alt="image" src="https://user-images.githubusercontent.com/66559869/204985803-35035202-4cb2-4b29-bb48-90a5f1e19f92.png">
/layouts/secondary.vue
<img width="905" alt="image" src="https://user-images.githubusercontent.com/66559869/204985866-ec27a16c-23f7-46a3-9b15-7c234f6f223d.png">

path: '/secondary/profile/fans/my-fans'
<img width="582" alt="image" src="https://user-images.githubusercontent.com/66559869/204986401-78dc292f-d9c9-4087-90f5-2b7535e1815e.png">

why I from 'main/home/recommend' to 'secondary/profile/fans/my-fans', 'my-fans' page render twice
I find that 'my-fans' page before 'secondary' render, after 'secondary' rendered, 'my-fans' render self once agin.
![image](https://user-images.githubusercontent.com/66559869/204987613-52634609-4187-4cdf-b0dc-96dd5a451fa9.png)

but I refresh my-fans that render is normal
![image](https://user-images.githubusercontent.com/66559869/204987802-e9430ab9-1ad5-401e-b5c2-6e52b97f4d5b.png)

**Comment by joeyhuang0235** [comment]
I've run into this issue as well.

**Comment by JohnCampionJr** [comment]
This is beyond the scope of this plugin.
