### ISSUE TITLE
ReferenceError: can't access lexical declaration 'layouts' before initialization

### ISSUE THREAD

**Issue by dewelooper** [JohnCampionJr/vite-plugin-vue-layouts#93]
Hello,
can somebody help me with this error?

Error points on my main.ts and this line:
```
const routes = setupLayouts(generatedRoutes)
```
variable is used here:
```
export const router = createRouter({
  history: createWebHistory(),
  routes,
})
```
(I didnt customize this package and usage in any aspect - it is working by default)

Strange is that this error occurs suddenly after some change and block rendering pages. Refreshing page change nothing, but when I stop vite and run "pnpm dev" it always start working for some time (sometimes for 10min but sometimes for 10h).

System is on development stage so I dont faced with this error on builded instance.

Please advice

Thank you
K.

**Comment by zhiyuanzmj** [comment]
Setting importMode to async can temporarily solve it.
https://github.com/posva/unplugin-vue-router/issues/132#issuecomment-1455691840
``` ts
import Layouts, { defaultImportMode } from 'vite-plugin-vue-layouts'

export default defineConfig({
 // ....
 plugins:[
   Layouts({
      importMode: process.env.NODE_ENV === 'production' ? defaultImportMode : () => 'async',
   }),
 ]
```

**Comment by JohnCampionJr** [comment]
Send along a reproduction repo and I'll try to take a look.  Not enough info here.
