### ISSUE TITLE
page gets reload when you put any assets in any folder of project.

### ISSUE THREAD

**Issue by alokVishu** [JohnCampionJr/vite-plugin-vue-layouts#94]
OS: macOS Ventura
browser: Chrome Version 109.0.5414.87 

When files or images are added to the project directory, the page is automatically reloaded, as demonstrated in the video located at https://vimeo.com/789694680.

[vite-layout-reload-issue.zip](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/files/10426035/vite-layout-reload-issue.zip)

**Comment by CapitaineCaverne** [comment]
https://github.com/JohnCampionJr/vite-plugin-vue-layouts/pull/101
