### ISSUE TITLE
Can we get update for this plugin which is supporting vite: ^4.0.0

### ISSUE THREAD

**Issue by Rajendar05** [JohnCampionJr/vite-plugin-vue-layouts#98]
Hi, currently this plugin has peer dependency with "vite": "^2.5.0 || ^3.0.0-0".
But now a day most of the other plugins are supporting vite: '^4.0.0'. due to this we are getting dependency conflicts.
Could you please provide update version of "vite-plugin-vue-layout" which peer dependency with "vite":"^4.0.0"

Thank you.

**Comment by kevinG73** [comment]
UP
