### ISSUE TITLE
Changes in scoped styles not applied until Vite reload. Vite 4.x

### ISSUE THREAD

**Issue by RobinvdGriend** [JohnCampionJr/vite-plugin-vue-layouts#99]
In Vite 4.x, using a `<style scoped>` block inside a layout SFC file will not have its classes or styles applied until restarting the dev server (reloading is not sufficient).

To reproduce:
1. Start the dev server `npm run dev`.
2. Add a `<style scoped>` block to an SFC used as a layout. Add a class and apply it to an element in the layout's template.
3. Load a page showing the layout. The style is not applied.
4. Restart the dev server. The style is now applied.

I did not test this on Vite 3.x, so I'm unsure whether its an incompatibility with the new major version or some other type of regression.

**Comment by kingyue737** [comment]
I met the same issue

**Comment by JohnCampionJr** [comment]
PR welcomed :)

**Comment by JohnCampionJr** [comment]
I cannot duplicate in Vitesse, with Vite 5.0.5
https://github.com/antfu/vitesse

If you find an issue with that template and Vite 5, please open a new issue
